apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: weather-agent-pipeline
description: application deployment pipeline
serialPipeline:
 stages:
 - targetId: dev-env
   profiles: [dev]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: dev-env
description: Cloud Run DEV service
run:
 location: projects/_PROJECT_ID/locations/europe-west1